### PR TITLE
Copy Ability Adjustments + small fix

### LINKED ISSUE #678: Kirby Copy Abilities consolidated jank.
Many of Kirby's copy abilities are non functional. This can manifest as move attributes not matching, tech not being inherited, broken animations or just straight up T-posing.

Mostly made this for documentation so multiple other issues can be consolidated. I will update this issue as I become aware of more. @Riah#5438 (me) on discord!

List of offenders:
Various cancellable charge moves - Air dodge instead of shield cancel
Sephiroth - T-pose
Sora - T-pose, pres
Fox/Falco - Land cancels
Hero - Frizz dash cancel
Aegis - T-Pose
Isabelle - Still vanilla pocket
Steve - Crashes the game
Lucas - Still uses PK freeze

### PR DESCRIPTION
**Pull request by ethangarsia517**
[assets.zip](https://github.com/HDR-Development/HewDraw-Remix/files/12502143/assets.zip)

Several Copy Abilities did not copy some of the new behavior that HDR added to some neutral specials in the game. This PR aims to fix that.

Should a character receive neutral special changes before this is pushed, they may or may not be adjusted for Kirby as well. Please let me know if there is a difference I may be missing here.

Lots of neutral specials also had some small frame data changes and have been matched. 
[Frame Data Changes.txt](https://github.com/HDR-Development/HewDraw-Remix/files/12447089/Frame.Data.Changes.txt)

**Main Changes:**

[+] Add Land Cancels for:
   - Fox
   - Bowser (auto transition into attack)
   - Falco
   - Zelda
   - Charizard (auto transition into attack)
   - Mr. Game & Watch
   - Dark Pit
   - Sora (Thundaga)
   - Banjo (on first shot)

[+] Add Fast Fall for lots of neutral specials in different statuses

[+] Add Aerial Drift for:
   - Link
   - Fox
   - Falco
   - Young Link
   - Toon Link
   - Mr. Game & Watch
   - Wolf
   - Bayonetta
   - Simon

[+] Add Airdodge Cancel on shoot for:
   - Diddy Kong
   - Wolf
   - Pac-Man
   - Mega Man
   - Sora (Firaga)

[+] Add Dash Cancel for:
   - Palutena (on hit)
   - Greninja (Max Charge)
   - Hero (Frizz, requires at least 13 mana and consumes 10)

[R] Add/Change Visual and Sound Effects for:
   - Mario
   - Luigi
   - Dr. Mario
   - Sonic
   - Palutena
   - Isabelle
   - King K. Rool
   - Mii Gunner

[!] Add PM-like Neutral Special Cancels

Bayonetta and Diddy Kong don't currently have animations for special canceling, so they are frame 1 for now.

**Copy Ability Changes:**

[!] PK Freeze: Kirby now harnesses the power of PSI, allowing him access to Offense Up.
   - Offense Up Changelog: [Offense Up Kirby.txt](https://github.com/HDR-Development/HewDraw-Remix/files/12447086/Offense.Up.Kirby.txt)

[+] Falcon Punch: can be turned around infinitely.
[+] Falcon Punch: adjusted KBG, BKB, and Damage output for aerial version to match Captain Falcon. This was an issue from vanilla Ultimate, now actually KOs.

[-] Giant Punch: Adjusted/removed hitboxes, damage, and KBG to match Donkey Kong.

[-] Bullet Climax: No longer gives Kirby Magic Series.

[/] Hadoken (Ken): Aerial version now shoots diagonally downwards.
(new animation)

[+] Plasma Breath: Can now go 💥 just like Ridley.
(new animation)

[!] Warlock Punch: Since Kirby loves to be in the air, he has learned how to Float just like Ganondorf instead.
(new animation)

[!] Bowser Firebreath: Kirby has mastered his firebreathing skills, and has learned how to shoot a powerful fireball just like Bowser.
(new animation)

[+] Straight Lunge: added jump and shield cancels.
(new animation)

[!] Ink Blaster: Repositioned hitbox, is not behind Kirby anymore.

**Other Changes:**

[+] Down Smash: Fixed a bug that caused the middle hitbox (ID2) damage to be decreased from 10 to 10 on late hit, when instead it was supposed to be one of the outer hitboxes (ID4) having its damage decreased from 14 to 10. All 4 outer hitboxes now have their damaged decreased to 10 on late hit.

[+] Hammer Flip: Can now drift and fastfall during the swing.

**Known Bugs:**
- Mii Gunner air to ground transition is broken when using the Heavy variant of Charge Shot.

Fixes #678

### CODE REVIEW

**Review by SkewedAskew — CHANGES_REQUESTED** [review]
One small thing:
- Nayru's Love should have 7 frames of landing lag as opposed to being a true land cancel. Her land cancel in opff sets the animation to a specific frame on landing, use that same logic

**Comment by ethangarsia517** [comment]
> One small thing:
> 
> * Nayru's Love should have 7 frames of landing lag as opposed to being a true land cancel. Her land cancel in opff sets the animation to a specific frame on landing, use that same logic

I think this should do the trick (matches Zelda's opff now.) Forgot about this one, it was before I found out that character specific statuses like these work for Kirby as well.

https://github.com/HDR-Development/HewDraw-Remix/pull/1821/commits/bf62c46a65cdd45ab1fa90aab9798d24d7735e91

File: fighters/kirby/src/opff.rs [hunk 1]
```diff
@@ -320,6 +899,260 @@ unsafe fn fastfall_specials(fighter: &mut L2CFighterCommon) {
         *FIGHTER_KIRBY_STATUS_KIND_SPECIAL_S_FALL,
         *FIGHTER_KIRBY_STATUS_KIND_SPECIAL_S_JUMP,
         *FIGHTER_KIRBY_STATUS_KIND_SPECIAL_S_ATTACK,
+        //copy abilities
```
Comment (SkewedAskew) [inline fighters/kirby/src/opff.rs]: Instead of checking every Kirby special_n status individually, try something like this:
```rs
let status = StatusModule::status_kind(fighter.module_accessor);
if (0x206..0x37c).contains(&status) {
  // do the thing
}
```
These two values should encompass the range of the Copy Ability statuses

**Review by SkewedAskew — DISMISSED** [review]

**Review by SkewedAskew — DISMISSED** [review]
Excellent work, very much appreciated

**Review by SkewedAskew — APPROVED** [review]
We'll need to keep a close eye out for any potential bugs, but great work
